glue = 0;
freeze = 0;
shielded = 0;
bigbloon = 10001;
electric = 0;
normal = 0;
camo = 0;
lead = 0;
regrow = 0;
stun = 0;
distraction = 0;
path = 0;
scr_Bloon_Paths();

corrosion = 0;
radiation = 0;
hitpoints = 3500 * global.bpower;
maxpoints = 3500 * global.bpower;
dmgpower = 25;
bloonmaxlayer = 0;
bloonlayer = 0;
tattered = 0;
action_set_alarm(15, 0);
fast = 2 * global.bspeed;
