glue = 0;
freeze = 0;
shielded = 0;
bigbloon = 10006;
electric = 0;
normal = 0;
camo = 0;
lead = 0;
regrow = 0;
stun = 0;
distraction = 0;
path = 0;
scr_Bloon_Paths();

corrosion = 0;
radiation = 0;
bloonmaxlayer = 0;
dmgpower = 9;
bloonlayer = 0;
hitpoints = 500 * global.bpower * bloonlayer;
maxpoints = 500 * global.bpower * bloonmaxlayer;
tattered = 0;
fast = 1 * global.bspeed;
