hit_id = noone;
hits = ds_list_create();
move = 0;

glue = 0;
freeze = 0;
shielded = 0;
bigbloon = 0;
electric = 0;
action_sprite_set(Red_Bloon_Spr, 0, 0);
path = 0;
normal = 1;
camo = 0;
lead = 0;
regrow = 0;
bloonmaxlayer = 0;
bloonlayer = 0;
tattered = 0;
stun = 0;
distraction = 0;
corrosion = 0;
radiation = 0;
fast = 1.5;
chipperhit = 0;
pophit = 0;
action_set_alarm(24, 5);
action_set_alarm(30, 11);
