function scr_load_career() {
	if (file_exists("file1.sav"))
	{
	    var loadFile =file_text_open_read("file1.sav");
	    var careerJson =file_text_read_string(loadFile);
    
	    var careerMap = json_decode(careerJson);
    
	    //extracting values
    
	_BP = ds_map_find_value(careerMap,"BP");
	_monkeymoney = ds_map_find_value(careerMap,"monkeymoney");
	_XP = ds_map_find_value(careerMap,"XP");
	_rank = ds_map_find_value(careerMap,"rank");
	_criteria = ds_map_find_value(careerMap,"criteria");
	_tr1 = ds_map_find_value(careerMap,"tr1");
	_tr2 = ds_map_find_value(careerMap,"tr2");
	_tr3 = ds_map_find_value(careerMap,"tr3");
	_tr4 = ds_map_find_value(careerMap,"tr4");
	_tr5 = ds_map_find_value(careerMap,"tr5");
	_tr6 = ds_map_find_value(careerMap,"tr6");
	_tr7 = ds_map_find_value(careerMap,"tr7");
	_tr8 = ds_map_find_value(careerMap,"tr8");
	_tr9 = ds_map_find_value(careerMap,"tr9");
	_tr10 = ds_map_find_value(careerMap,"tr10");
	_tr11 = ds_map_find_value(careerMap,"tr11");
	_tr12 = ds_map_find_value(careerMap,"tr12");
	_tr13 = ds_map_find_value(careerMap,"tr13");
	_tr14 = ds_map_find_value(careerMap,"tr14");
	_tr15 = ds_map_find_value(careerMap,"tr15");
	_tr16 = ds_map_find_value(careerMap,"tr16");

	_tr1x = ds_map_find_value(careerMap,"tr1x");
	_tr2x = ds_map_find_value(careerMap,"tr2x");
	_tr3x = ds_map_find_value(careerMap,"tr3x");
	_tr4x = ds_map_find_value(careerMap,"tr4x");
	_tr5x = ds_map_find_value(careerMap,"tr5x");
	_tr6x = ds_map_find_value(careerMap,"tr6x");
	_tr7x = ds_map_find_value(careerMap,"tr7x");
	_tr8x = ds_map_find_value(careerMap,"tr8x");
	_tr9x = ds_map_find_value(careerMap,"tr9x");
	_tr10x = ds_map_find_value(careerMap,"tr10x");
	_tr11x = ds_map_find_value(careerMap,"tr11x");
	_tr12x = ds_map_find_value(careerMap,"tr12x");
	_tr13x = ds_map_find_value(careerMap,"tr13x");
	_tr14x = ds_map_find_value(careerMap,"tr14x");
	_tr15x = ds_map_find_value(careerMap,"tr15x");
	_tr16x = ds_map_find_value(careerMap,"tr16x");

	_s1 = ds_map_find_value(careerMap,"s1");
	_s2 = ds_map_find_value(careerMap,"s2");
	_s3 = ds_map_find_value(careerMap,"s3");
	_s4 = ds_map_find_value(careerMap,"s4");
	_s5 = ds_map_find_value(careerMap,"s5");
	_s6 = ds_map_find_value(careerMap,"s6");
	_s7 = ds_map_find_value(careerMap,"s7");
	_s8 = ds_map_find_value(careerMap,"s8");
	_s9 = ds_map_find_value(careerMap,"s9");
	_s10 = ds_map_find_value(careerMap,"s10");
	_s11 = ds_map_find_value(careerMap,"s11");
	_s12 = ds_map_find_value(careerMap,"s12");

	_bw1 = ds_map_find_value(careerMap,"bw1");
	_bw2 = ds_map_find_value(careerMap,"bw2");
	_bw3 = ds_map_find_value(careerMap,"bw3");
	_bw4 = ds_map_find_value(careerMap,"bw4");
	_bw5 = ds_map_find_value(careerMap,"bw5");
	_bw6 = ds_map_find_value(careerMap,"bw6");
	_bw7 = ds_map_find_value(careerMap,"bw7");
	_bw8 = ds_map_find_value(careerMap,"bw8");
	_bw9 = ds_map_find_value(careerMap,"bw9");
	_bw10 = ds_map_find_value(careerMap,"bw10");
	_bw11 = ds_map_find_value(careerMap,"bw11");
	_bw12 = ds_map_find_value(careerMap,"bw12");
	_bw13 = ds_map_find_value(careerMap,"bw13");
	_bw14 = ds_map_find_value(careerMap,"bw14");
	_bw15 = ds_map_find_value(careerMap,"bw15");
	_bw16 = ds_map_find_value(careerMap,"bw16");

	_bwx1 = ds_map_find_value(careerMap,"bwx1");
	_bwx2 = ds_map_find_value(careerMap,"bwx2");
	_bwx3 = ds_map_find_value(careerMap,"bwx3");
	_bwx4 = ds_map_find_value(careerMap,"bwx4");
	_bwx5 = ds_map_find_value(careerMap,"bwx5");
	_bwx6 = ds_map_find_value(careerMap,"bwx6");
	_bwx7 = ds_map_find_value(careerMap,"bwx7");
	_bwx8 = ds_map_find_value(careerMap,"bwx8");
	_bwx9 = ds_map_find_value(careerMap,"bwx9");
	_bwx10 = ds_map_find_value(careerMap,"bwx10");
	_bwx11 = ds_map_find_value(careerMap,"bwx11");
	_bwx12 = ds_map_find_value(careerMap,"bwx12");
	_bwx13 = ds_map_find_value(careerMap,"bwx13");
	_bwx14 = ds_map_find_value(careerMap,"bwx14");
	_bwx15 = ds_map_find_value(careerMap,"bwx15");
	_bwx16 = ds_map_find_value(careerMap,"bwx16");

	_DML = ds_map_find_value(careerMap,"DML");
	_DMM = ds_map_find_value(careerMap,"DMM");
	_DMR = ds_map_find_value(careerMap,"DMR");
	_TSL = ds_map_find_value(careerMap,"TSL");
	_TSM = ds_map_find_value(careerMap,"TSM");
	_TSR = ds_map_find_value(careerMap,"TSR");
	_BML = ds_map_find_value(careerMap,"BML");
	_BMM = ds_map_find_value(careerMap,"BMM");
	_BMR = ds_map_find_value(careerMap,"BMR");
	_SnML = ds_map_find_value(careerMap,"SnML");
	_SnMM = ds_map_find_value(careerMap,"SnMM");
	_SnMR = ds_map_find_value(careerMap,"SnMR");
	_NML = ds_map_find_value(careerMap,"NML");
	_NMM = ds_map_find_value(careerMap,"NMM");
	_NMR = ds_map_find_value(careerMap,"NMR");
	_BCL = ds_map_find_value(careerMap,"BCL");
	_BCM = ds_map_find_value(careerMap,"BCM");
	_BCR = ds_map_find_value(careerMap,"BCR");
	_MSL = ds_map_find_value(careerMap,"MSL");
	_MSM = ds_map_find_value(careerMap,"MSM");
	_MSR = ds_map_find_value(careerMap,"MSR");
	_CTL = ds_map_find_value(careerMap,"CTL");
	_CTM = ds_map_find_value(careerMap,"CTM");
	_CTR = ds_map_find_value(careerMap,"CTR");

	_GGL = ds_map_find_value(careerMap,"GGL");
	_GGM = ds_map_find_value(careerMap,"GGM");
	_GGR = ds_map_find_value(careerMap,"GGR");
	_IML = ds_map_find_value(careerMap,"IML");
	_IMM = ds_map_find_value(careerMap,"IMM");
	_IMR = ds_map_find_value(careerMap,"IMR");
	_MBL = ds_map_find_value(careerMap,"MBL");
	_MBM = ds_map_find_value(careerMap,"MBM");
	_MBR = ds_map_find_value(careerMap,"MBR");
	_MEL = ds_map_find_value(careerMap,"MEL");
	_MEM = ds_map_find_value(careerMap,"MEM");
	_MER = ds_map_find_value(careerMap,"MER");
	_MAL = ds_map_find_value(careerMap,"MAL");
	_MAM = ds_map_find_value(careerMap,"MAM");
	_MAR = ds_map_find_value(careerMap,"MAR");
	_BChL = ds_map_find_value(careerMap,"BChL");
	_BChM = ds_map_find_value(careerMap,"BChM");
	_BChR = ds_map_find_value(careerMap,"BChR");
	_MApL = ds_map_find_value(careerMap,"MApL");
	_MApM = ds_map_find_value(careerMap,"MApM");
	_MApR = ds_map_find_value(careerMap,"MApR");
	_MAlL = ds_map_find_value(careerMap,"MAlL");
	_MAlM = ds_map_find_value(careerMap,"MAlM");
	_MAlR = ds_map_find_value(careerMap,"MAlR");

	_MVL = ds_map_find_value(careerMap,"MVL");
	_MVM = ds_map_find_value(careerMap,"MVM");
	_MVR = ds_map_find_value(careerMap,"MVR");
	_BTL = ds_map_find_value(careerMap,"BTL");
	_BTM = ds_map_find_value(careerMap,"BTM");
	_BTR = ds_map_find_value(careerMap,"BTR");
	_DGL = ds_map_find_value(careerMap,"DGL");
	_DGM = ds_map_find_value(careerMap,"DGM");
	_DGR = ds_map_find_value(careerMap,"DGR");
	_MLL = ds_map_find_value(careerMap,"MLL");
	_MLM = ds_map_find_value(careerMap,"MLM");
	_MLR = ds_map_find_value(careerMap,"MLR");
	_HPL = ds_map_find_value(careerMap,"HPL");
	_HPM = ds_map_find_value(careerMap,"HPM");
	_HPR = ds_map_find_value(careerMap,"HPR");
	_SFL = ds_map_find_value(careerMap,"SFL");
	_SFM = ds_map_find_value(careerMap,"SFM");
	_SFR = ds_map_find_value(careerMap,"SFR");
	_PML = ds_map_find_value(careerMap,"PML");
	_PMM = ds_map_find_value(careerMap,"PMM");
	_PMR = ds_map_find_value(careerMap,"PMR");
	_SuML = ds_map_find_value(careerMap,"SuML");
	_SuMM = ds_map_find_value(careerMap,"SuMM");
	_SuMR = ds_map_find_value(careerMap,"SuMR");
	_angrysquirrel = ds_map_find_value(careerMap,"angrysquirrel");
	_bloonburybush = ds_map_find_value(careerMap,"bloonburybush");
	_sprinkler = ds_map_find_value(careerMap,"sprinkler");
	_monkeynurse = ds_map_find_value(careerMap,"monkeynurse");
	_careershow = ds_map_find_value(careerMap,"careershow");

	_b1 = ds_map_find_value(careerMap,"b1");
	_b2 = ds_map_find_value(careerMap,"b2");
	_b3 = ds_map_find_value(careerMap,"b3");
	_b4 = ds_map_find_value(careerMap,"b4");
	_b5 = ds_map_find_value(careerMap,"b5");
	_b6 = ds_map_find_value(careerMap,"b6");
	_b7 = ds_map_find_value(careerMap,"b7");
	_b8 = ds_map_find_value(careerMap,"b8");
	_b9 = ds_map_find_value(careerMap,"b9");
	_b10 = ds_map_find_value(careerMap,"b10");
	_b11 = ds_map_find_value(careerMap,"b11");
	_b12 = ds_map_find_value(careerMap,"b12");


	_xx1 = ds_map_find_value(careerMap,"xx1");
	_xx2 = ds_map_find_value(careerMap,"xx2");
	_xx3 = ds_map_find_value(careerMap,"xx3");
	_xx4 = ds_map_find_value(careerMap,"xx4");
	_xx5 = ds_map_find_value(careerMap,"xx5");
	_xx6 = ds_map_find_value(careerMap,"xx6");
	_xx7 = ds_map_find_value(careerMap,"xx7");
	_xx8 = ds_map_find_value(careerMap,"xx8");
	_xx9 = ds_map_find_value(careerMap,"xx9");
	_xx10 = ds_map_find_value(careerMap,"xx10");
	_xx11 = ds_map_find_value(careerMap,"xx11");
	_xx12 = ds_map_find_value(careerMap,"xx12");
	_xx13 = ds_map_find_value(careerMap,"xx13");
	_xx14 = ds_map_find_value(careerMap,"xx14");
	_xx15 = ds_map_find_value(careerMap,"xx15");
	_xx16 = ds_map_find_value(careerMap,"xx16");

	_x1 = ds_map_find_value(careerMap,"x1");
	_x2 = ds_map_find_value(careerMap,"x2");
	_x3 = ds_map_find_value(careerMap,"x3");
	_x4 = ds_map_find_value(careerMap,"x4");
	_x5 = ds_map_find_value(careerMap,"x5");
	_x6 = ds_map_find_value(careerMap,"x6");
	_x7 = ds_map_find_value(careerMap,"x7");
	_x8 = ds_map_find_value(careerMap,"x8");
	_x9 = ds_map_find_value(careerMap,"x9");
	_x10 = ds_map_find_value(careerMap,"x10");
	_x11 = ds_map_find_value(careerMap,"x11");
	_x12 = ds_map_find_value(careerMap,"x12");
	_x13 = ds_map_find_value(careerMap,"x13");
	_x14 = ds_map_find_value(careerMap,"x14");
	_x15 = ds_map_find_value(careerMap,"x15");
	_x16 = ds_map_find_value(careerMap,"x16");

	_t1 = ds_map_find_value(careerMap,"t1");
	_t2 = ds_map_find_value(careerMap,"t2");
	_t3 = ds_map_find_value(careerMap,"t3");
	_t4 = ds_map_find_value(careerMap,"t4");
	_t5 = ds_map_find_value(careerMap,"t5");
	_t6 = ds_map_find_value(careerMap,"t6");
	_t7 = ds_map_find_value(careerMap,"t7");
	_t8 = ds_map_find_value(careerMap,"t8");
	_t9 = ds_map_find_value(careerMap,"t9");
	_t10 = ds_map_find_value(careerMap,"t10");
	_t11 = ds_map_find_value(careerMap,"t11");
	_t12 = ds_map_find_value(careerMap,"t12");
	_t13 = ds_map_find_value(careerMap,"t13");
	_t14 = ds_map_find_value(careerMap,"t14");
	_t15 = ds_map_find_value(careerMap,"t15");
	_t16 = ds_map_find_value(careerMap,"t16");

	    with instance_create (x,y,Career_Control)
	    {
	DML = other._DML
	DMM = other._DMM
	DMR = other._DMR
	TSL = other._TSL
	TSM = other._TSM
	TSR = other._TSR
	BML = other._BML
	BMM = other._BMM
	BMR = other._BMR
	SnML = other._SnML
	SnMM = other._SnMM
	SnMR = other._SnMR
	NML = other._NML
	NMM = other._NMM
	NMR = other._NMR
	BCL = other._BCL
	BCM = other._BCM
	BCR = other._BCR
	MSL = other._MSL
	MSM = other._MSM
	MSR = other._MSR
	CTL = other._CTL
	CTM = other._CTM
	CTR = other._CTR

	GGL = other._GGL
	GGM = other._GGM
	GGR = other._GGR
	IML = other._IML
	IMM = other._IMM
	IMR = other._IMR
	MBL = other._MBL
	MBM = other._MBM
	MBR = other._MBR
	MEL = other._MEL
	MEM = other._MEM
	MER = other._MER
	MAL = other._MAL
	MAM = other._MAM
	MAR = other._MAR
	BChL = other._BChL
	BChM = other._BChM
	BChR = other._BChR
	MApL = other._MApL
	MApM = other._MApM
	MApR = other._MApR
	MAlL = other._MAlL
	MAlM = other._MAlM
	MAlR = other._MAlR

	MVL = other._MVL
	MVM = other._MVM
	MVR = other._MVR
	BTL = other._BTL
	BTM = other._BTM
	BTR = other._BTR
	DGL = other._DGL
	DGM = other._DGM
	DGR = other._DGR
	MLL = other._MLL
	MLM = other._MLM
	MLR = other._MLR
	HPL = other._HPL
	HPM = other._HPM
	HPR = other._HPR
	SFL = other._SFL
	SFM = other._SFM
	SFR = other._SFR
	PML = other._PML
	PMM = other._PMM
	PMR = other._PMR
	SuML = other._SuML
	SuMM = other._SuMM
	SuMR = other._SuMR

	XP = other._XP
	rank = other._rank
	BP = other._BP
	monkeymoney = other._monkeymoney
	criteria = other._criteria

	tr1 = other._tr1
	tr2 = other._tr2
	tr3 = other._tr3
	tr4 = other._tr4
	tr5 = other._tr5
	tr6 = other._tr6
	tr7 = other._tr7
	tr8 = other._tr8 
	tr9 = other._tr9
	tr10 = other._tr10 
	tr11 = other._tr11 
	tr12 = other._tr12 
	tr13 = other._tr13 
	tr14 = other._tr14
	tr15 = other._tr15 
	tr16 = other._tr16 

	s1 = other._s1
	s2 = other._s2
	s3 = other._s3
	s4 = other._s4
	s5 = other._s5
	s6 = other._s6
	s7 = other._s7
	s8 = other._s8
	s9 = other._s9
	s10 = other._s10
	s11 = other._s11
	s12 = other._s12

	tr1x = other._tr1x
	tr2x = other._tr2x 
	tr3x = other._tr3x 
	tr4x = other._tr4x
	tr5x = other._tr5x 
	tr6x = other._tr6x 
	tr7x = other._tr7x 
	tr8x = other._tr8x
	tr9x = other._tr9x 
	tr10x = other._tr10x 
	tr11x = other._tr11x
	tr12x = other._tr12x 
	tr13x = other._tr13x 
	tr14x = other._tr14x 
	tr15x = other._tr15x 
	tr16x = other._tr16x 

	bw1 = other._bw1
	bw2 = other._bw2 
	bw3 = other._bw3 
	bw4 = other._bw4 
	bw5 = other._bw5 
	bw6 = other._bw6
	bw7 = other._bw7 
	bw8 = other._bw8 
	bw9 = other._bw9
	bw10 = other._bw10 
	bw11 = other._bw11 
	bw12 = other._bw12 
	bw13 = other._bw13
	bw14 = other._bw14
	bw15 = other._bw15
	bw16 = other._bw16 

	bwx1 = other._bwx1
	bwx2 = other._bwx2 
	bwx3 = other._bwx3 
	bwx4 = other._bwx4 
	bwx5 = other._bwx5 
	bwx6 = other._bwx6
	bwx7 = other._bwx7 
	bwx8 = other._bwx8
	bwx9 = other._bwx9 
	bwx10 = other._bwx10 
	bwx11 = other._bwx11 
	bwx12 = other._bwx12 
	bwx13 = other._bwx13 
	bwx14 = other._bwx14 
	bwx15 = other._bwx15 
	bwx16 = other._bwx16 

	x1 = other._x1
	x2 = other._x2 
	x3 = other._x3 
	x4 = other._x4 
	x5 = other._x5 
	x6 = other._x6
	x7 = other._x7 
	x8 = other._x8 
	x9 = other._x9
	x10 = other._x10 
	x11 = other._x11 
	x12 = other._x12 
	x13 = other._x13
	x14 = other._x14
	x15 = other._x15
	x16 = other._x16 

	t1 = other._t1
	t2 = other._t2 
	t3 = other._t3 
	t4 = other._t4 
	t5 = other._t5 
	t6 = other._t6
	t7 = other._t7 
	t8 = other._t8 
	t9 = other._t9
	t10 = other._t10 
	t11 = other._t11 
	t12 = other._t12 
	t13 = other._t13
	t14 = other._t14
	t15 = other._t15
	t16 = other._t16 

	xx1 = other._xx1
	xx2 = other._xx2 
	xx3 = other._xx3 
	xx4 = other._xx4 
	xx5 = other._xx5 
	xx6 = other._xx6
	xx7 = other._xx7 
	xx8 = other._xx8 
	xx9 = other._xx9
	xx10 = other._xx10 
	xx11 = other._xx11 
	xx12 = other._xx12 
	xx13 = other._xx13
	xx14 = other._xx14
	xx15 = other._xx15
	xx16 = other._xx16 

	b1 = other._b1
	b2 = other._b2 
	b3 = other._b3 
	b4 = other._b4 
	b5 = other._b5 
	b6 = other._b6
	b7 = other._b7 
	b8 = other._b8 
	b9 = other._b9
	b10 = other._b10 
	b11 = other._b11 
	b12 = other._b12 


	angrysquirrel = other._angrysquirrel
	bloonburybush = other._bloonburybush
	sprinkler = other._sprinkler
	monkeynurse = other._monkeynurse
	careershow = other._careershow

	    }
    
	file_text_close(loadFile);
	ds_map_destroy(careerMap);


	}



}
