action_sprite_set(Bully_Bloon_Layers, 2, 0);
glue = 0;
freeze = 0;
shielded = 0;
bigbloon = 10001;
electric = 0;
normal = 0;
camo = 0;
lead = 0;
regrow = 0;
stun = 0;
distraction = 0;
path = 0;
scr_Bloon_Paths();

corrosion = 0;
radiation = 0;
hitpoints = 1500 * global.bpower;
maxpoints = 1500 * global.bpower;
dmgpower = 2;
bloonmaxlayer = 0;
bloonlayer = 0;
tattered = 0;
fast = 1 * global.bspeed;
