glue = 0;
freeze = 0;
shielded = 0;
bigbloon = 10007;
electric = 0;
normal = 0;
camo = 0;
lead = 0;
regrow = 0;
stun = 0;
distraction = 0;
path = 0;
scr_Bloon_Paths();

corrosion = 0;
radiation = 0;
hitpoints = 6000 * global.bpower;
maxpoints = 6000 * global.bpower;
dmgpower = 100;
bloonmaxlayer = 0;
bloonlayer = 0;
tattered = 0;
fast = 0.5 * global.bspeed;
action_set_alarm(2, 0);
action_set_alarm(600, 1);
