if global.normalmodeselect = 1 {
if global.wave >= 6
image_index = 1
if global.wave >= 8
image_index = 2
if global.wave >= 12
image_index = 3
if global.wave >= 16
image_index = 4
if global.wave >= 20
image_index = 5
if global.wave >= 23
image_index = 6
if global.wave >= 30
image_index = 7
if global.wave >= 32
image_index = 8
if global.wave >= 40
image_index = 9
if global.wave >= 57
image_index = 10
if global.wave >= 59
image_index = 11
if global.wave >= 70
image_index = 12
if global.wave >= 78
image_index = 13
if global.wave >= 82
image_index = 14
}

if global.nightmaremodeselect = 1 {
if global.wave >= 9
image_index = 15
if global.wave >= 15
image_index = 16
if global.wave >= 18
image_index = 17
if global.wave >= 19
image_index = 18
if global.wave >= 20
image_index = 19
if global.wave >= 24
image_index = 20
if global.wave >= 28
image_index = 21
if global.wave >= 30
image_index = 22
if global.wave >= 40
image_index = 23
if global.wave >= 44
image_index = 24
if global.wave >= 47
image_index = 25
if global.wave >= 54
image_index = 26
if global.wave >= 55
image_index = 27
if global.wave >= 60
image_index = 28
}

