glue = 0;
freeze = 0;
shielded = 0;
bigbloon = 105;
electric = 0;
action_sprite_set(Red_Bloon_Spr, 0, 0);
path = 0;
scr_Bloon_Paths();

normal = 1;
blimp = 0;
camo = 0;
lead = 0;
regrow = 0;
bloonmaxlayer = 0;
bloonlayer = 0;
tattered = 0;
stun = 0;
corrosion = 0;
radiation = 0;
distraction = 0;
fast = 2;
action_set_alarm(30, 0);
action_set_alarm(24, 5);
