function scr_bettersave_career() {
	if (file_exists("bettersave.sav"))
	{
	file_delete("bettersave.sav");
	}


	/*
	var saveFile = file_text_open_write("file3.sav");

	var "BTDX" = ds_map_create();
	*/


	ini_open("bettersave.sav")

	/*
	for(i = 0; i <= 999; i++) {
	    ini_write_real("Recollection", "recollectionWeap" + string(i), global.recollectionWeap[i]);
	}
	for(i = 0; i <= 199; i++) {
	    ini_write_real("Recollection", "recollectionBoss" + string(i), global.recollectionBoss[i]);
	}
	for(i = 0; i <= 99; i++) {
	    ini_write_real("Recollection", "recollectionA" + string(i), global.recollectionA[i]);
	    ini_write_real("Recollection", "recollectionB" + string(i), global.recollectionB[i]);
	    ini_write_real("Recollection", "recollectionC" + string(i), global.recollectionC[i]);
	    ini_write_real("Recollection", "recollectionD" + string(i), global.recollectionD[i]);
	    ini_write_real("Recollection", "recollectionE" + string(i), global.recollectionE[i]);
	    ini_write_real("Recollection", "recollectionF" + string(i), global.recollectionF[i]);
	    ini_write_real("Recollection", "recollectionG" + string(i), global.recollectionG[i]);
	    ini_write_real("Recollection", "recollectionH" + string(i), global.recollectionH[i]);
	    ini_write_real("Recollection", "recollectionJ" + string(i), global.recollectionJ[i]);
	    ini_write_real("Recollection", "recollectionK" + string(i), global.recollectionK[i]);
		ini_write_real("Recollection", "recollectionL" + string(i), global.recollectionL[i]);
	    ini_write_real("Recollection", "recollectionM" + string(i), global.recollectionM[i]);
		ini_write_real("Recollection", "recollectionP" + string(i), global.recollectionP[i]);
	    ini_write_real("Recollection", "recollectionR" + string(i), global.recollectionR[i]);
		ini_write_real("Recollection", "recollectionS" + string(i), global.recollectionS[i]);
		ini_write_real("Recollection", "recollectionT" + string(i), global.recollectionT[i]);
		ini_write_real("Recollection", "recollectionU" + string(i), global.recollectionU[i]);
		ini_write_real("Recollection", "recollectionV" + string(i), global.recollectionV[i]);
		ini_write_real("Recollection", "recollectionW" + string(i), global.recollectionW[i]);
    
	    //ini_write_real("Recollection", "recollectionA" + string(i), global.recollectionA[i]);
	}

	ini_write_real("Recollection", "gameTutorial", global.gameTutorial);
	ini_write_real("Recollection", "gameSound", global.gameSound);
	ini_write_real("Recollection", "gameMusic", global.gameMusic);
	ini_write_real("Recollection", "gameFocusPause", global.gameFocusPause);
	ini_write_real("Recollection", "gameDamageDisplay", global.gameDamageDisplay);
	*/

	ini_write_real("BTDX", "trackmilestone17", global.track17milestone);
	ini_write_real("BTDX", "trackmilestone18", global.track18milestone);
	ini_write_real("BTDX", "trackmilestone19", global.track19milestone);
	ini_write_real("BTDX", "trackmilestone20", global.track20milestone);
	ini_write_real("BTDX", "trackmilestone21", global.track21milestone);
	ini_write_real("BTDX", "trackmilestone22", global.track22milestone);
	ini_write_real("BTDX", "trackmilestone23", global.track23milestone);
	ini_write_real("BTDX", "trackmilestone24", global.track24milestone);
	ini_write_real("BTDX", "trackmilestone25", global.track25milestone);
	ini_write_real("BTDX", "trackmilestone26", global.track26milestone);
	ini_write_real("BTDX", "trackmilestone27", global.track27milestone);
	ini_write_real("BTDX", "trackmilestone28", global.track28milestone);
	ini_write_real("BTDX", "trackmilestone29", global.track29milestone);
	ini_write_real("BTDX", "trackmilestone30", global.track30milestone);
	ini_write_real("BTDX", "trackmilestone31", global.track31milestone);
	ini_write_real("BTDX", "trackmilestone32", global.track32milestone);
	ini_write_real("BTDX", "trackmilestone33", global.track33milestone);
	ini_write_real("BTDX", "trackmilestone34", global.track34milestone);
	ini_write_real("BTDX", "trackmilestone35", global.track35milestone);
	ini_write_real("BTDX", "trackmilestone36", global.track36milestone);
	ini_write_real("BTDX", "trackmilestone37", global.track37milestone);
	ini_write_real("BTDX", "trackmilestone38", global.track38milestone);
	ini_write_real("BTDX", "trackmilestone39", global.track39milestone);

	ini_write_real("BTDX", "trackimpopmilestone17", global.track17hardstone);
	ini_write_real("BTDX", "trackimpopmilestone18", global.track18hardstone);
	ini_write_real("BTDX", "trackimpopmilestone19", global.track19hardstone);
	ini_write_real("BTDX", "trackimpopmilestone20", global.track20hardstone);
	ini_write_real("BTDX", "trackimpopmilestone21", global.track21hardstone);
	ini_write_real("BTDX", "trackimpopmilestone22", global.track22hardstone);
	ini_write_real("BTDX", "trackimpopmilestone23", global.track23hardstone);
	ini_write_real("BTDX", "trackimpopmilestone24", global.track24hardstone);
	ini_write_real("BTDX", "trackimpopmilestone25", global.track25hardstone);
	ini_write_real("BTDX", "trackimpopmilestone26", global.track26hardstone);
	ini_write_real("BTDX", "trackimpopmilestone27", global.track27hardstone);
	ini_write_real("BTDX", "trackimpopmilestone28", global.track28hardstone);
	ini_write_real("BTDX", "trackimpopmilestone29", global.track29hardstone);
	ini_write_real("BTDX", "trackimpopmilestone30", global.track30hardstone);
	ini_write_real("BTDX", "trackimpopmilestone31", global.track31hardstone);
	ini_write_real("BTDX", "trackimpopmilestone32", global.track32hardstone);
	ini_write_real("BTDX", "trackimpopmilestone33", global.track33hardstone);
	ini_write_real("BTDX", "trackimpopmilestone34", global.track34hardstone);
	ini_write_real("BTDX", "trackimpopmilestone35", global.track35hardstone);
	ini_write_real("BTDX", "trackimpopmilestone36", global.track36hardstone);
	ini_write_real("BTDX", "trackimpopmilestone37", global.track37hardstone);
	ini_write_real("BTDX", "trackimpopmilestone38", global.track38hardstone);
	ini_write_real("BTDX", "trackimpopmilestone39", global.track39hardstone);

	ini_write_real("BTDX", "trackbestwave17", global.track17bestwave);
	ini_write_real("BTDX", "trackbestwave18", global.track18bestwave);
	ini_write_real("BTDX", "trackbestwave19", global.track19bestwave);
	ini_write_real("BTDX", "trackbestwave20", global.track20bestwave);
	ini_write_real("BTDX", "trackbestwave21", global.track21bestwave);
	ini_write_real("BTDX", "trackbestwave22", global.track22bestwave);
	ini_write_real("BTDX", "trackbestwave23", global.track23bestwave);
	ini_write_real("BTDX", "trackbestwave24", global.track24bestwave);
	ini_write_real("BTDX", "trackbestwave25", global.track25bestwave);
	ini_write_real("BTDX", "trackbestwave26", global.track26bestwave);
	ini_write_real("BTDX", "trackbestwave27", global.track27bestwave);
	ini_write_real("BTDX", "trackbestwave28", global.track28bestwave);
	ini_write_real("BTDX", "trackbestwave29", global.track29bestwave);
	ini_write_real("BTDX", "trackbestwave30", global.track30bestwave);
	ini_write_real("BTDX", "trackbestwave31", global.track31bestwave);
	ini_write_real("BTDX", "trackbestwave32", global.track32bestwave);
	ini_write_real("BTDX", "trackbestwave33", global.track33bestwave);
	ini_write_real("BTDX", "trackbestwave34", global.track34bestwave);
	ini_write_real("BTDX", "trackbestwave35", global.track35bestwave);
	ini_write_real("BTDX", "trackbestwave36", global.track36bestwave);
	ini_write_real("BTDX", "trackbestwave37", global.track37bestwave);
	ini_write_real("BTDX", "trackbestwave38", global.track38bestwave);
	ini_write_real("BTDX", "trackbestwave39", global.track39bestwave);

	ini_write_real("BTDX", "trackbestimpopwave17", global.track17besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave18", global.track18besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave19", global.track19besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave20", global.track20besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave21", global.track21besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave22", global.track22besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave23", global.track23besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave24", global.track24besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave25", global.track25besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave26", global.track26besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave27", global.track27besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave28", global.track28besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave29", global.track29besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave30", global.track30besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave31", global.track31besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave32", global.track32besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave33", global.track33besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave34", global.track34besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave35", global.track35besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave36", global.track36besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave37", global.track37besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave38", global.track38besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave39", global.track39besthardwave);

	ini_write_real("BTDX", "trackscore17", global.x17);
	ini_write_real("BTDX", "trackscore18", global.x18);
	ini_write_real("BTDX", "trackscore19", global.x19);
	ini_write_real("BTDX", "trackscore20", global.x20);
	ini_write_real("BTDX", "trackscore21", global.x21);
	ini_write_real("BTDX", "trackscore22", global.x22);
	ini_write_real("BTDX", "trackscore23", global.x23);
	ini_write_real("BTDX", "trackscore24", global.x24);
	ini_write_real("BTDX", "trackscore25", global.x25);
	ini_write_real("BTDX", "trackscore26", global.x26);
	ini_write_real("BTDX", "trackscore27", global.x27);
	ini_write_real("BTDX", "trackscore28", global.x28);
	ini_write_real("BTDX", "trackscore29", global.x29);
	ini_write_real("BTDX", "trackscore30", global.x30);
	ini_write_real("BTDX", "trackscore31", global.x31);
	ini_write_real("BTDX", "trackscore32", global.x32);
	ini_write_real("BTDX", "trackscore33", global.x33);
	ini_write_real("BTDX", "trackscore34", global.x34);
	ini_write_real("BTDX", "trackscore35", global.x35);
	ini_write_real("BTDX", "trackscore36", global.x36);
	ini_write_real("BTDX", "trackscore37", global.x37);
	ini_write_real("BTDX", "trackscore38", global.x38);
	ini_write_real("BTDX", "trackscore39", global.x39);

	ini_write_real("BTDX", "tracktime17", global.t17);
	ini_write_real("BTDX", "tracktime18", global.t18);
	ini_write_real("BTDX", "tracktime19", global.t19);
	ini_write_real("BTDX", "tracktime20", global.t20);
	ini_write_real("BTDX", "tracktime21", global.t21);
	ini_write_real("BTDX", "tracktime22", global.t22);
	ini_write_real("BTDX", "tracktime23", global.t23);
	ini_write_real("BTDX", "tracktime24", global.t24);
	ini_write_real("BTDX", "tracktime25", global.t25);
	ini_write_real("BTDX", "tracktime26", global.t26);
	ini_write_real("BTDX", "tracktime27", global.t27);
	ini_write_real("BTDX", "tracktime28", global.t28);
	ini_write_real("BTDX", "tracktime29", global.t29);
	ini_write_real("BTDX", "tracktime30", global.t30);
	ini_write_real("BTDX", "tracktime31", global.t31);
	ini_write_real("BTDX", "tracktime32", global.t32);
	ini_write_real("BTDX", "tracktime33", global.t33);
	ini_write_real("BTDX", "tracktime34", global.t34);
	ini_write_real("BTDX", "tracktime35", global.t35);
	ini_write_real("BTDX", "tracktime36", global.t36);
	ini_write_real("BTDX", "tracktime37", global.t37);
	ini_write_real("BTDX", "tracktime38", global.t38);
	ini_write_real("BTDX", "tracktime39", global.t39);

	/*
	ini_write_real("BTDX", "xx17", global.xx17);
	ini_write_real("BTDX", "xx18", global.xx18);
	ini_write_real("BTDX", "xx19", global.xx19);
	ini_write_real("BTDX", "xx20", global.xx20);
	ini_write_real("BTDX", "xx21", global.xx21);
	ini_write_real("BTDX", "xx22", global.xx22);
	ini_write_real("BTDX", "xx23", global.xx23);
	ini_write_real("BTDX", "xx24", global.xx24);
	ini_write_real("BTDX", "xx25", global.xx25);
	ini_write_real("BTDX", "xx26", global.xx26);
	ini_write_real("BTDX", "xx27", global.xx27);
	ini_write_real("BTDX", "xx28", global.xx28);
	ini_write_real("BTDX", "xx29", global.xx29);
	ini_write_real("BTDX", "xx30", global.xx30);
	ini_write_real("BTDX", "xx31", global.xx31);
	ini_write_real("BTDX", "xx32", global.xx32);
	ini_write_real("BTDX", "xx33", global.xx33);
	ini_write_real("BTDX", "xx34", global.xx34);
	ini_write_real("BTDX", "xx35", global.xx35);
	ini_write_real("BTDX", "xx36", global.xx36);
	ini_write_real("BTDX", "xx37", global.xx37);
	ini_write_real("BTDX", "xx38", global.xx38);
	ini_write_real("BTDX", "xx39", global.xx39);
	*/

	ini_write_real("BTDX", "XP", global.XP);
	ini_write_real("BTDX", "BP", global.BP);
	ini_write_real("BTDX", "monkeymoney", global.monkeymoney);
	ini_write_real("BTDX", "rank", global.rank);
	ini_write_real("BTDX", "criteria", global.criteria);
	ini_write_real("BTDX", "trackmilestone1", global.track1milestone);
	ini_write_real("BTDX", "trackmilestone2", global.track2milestone);
	ini_write_real("BTDX", "trackmilestone3", global.track3milestone);
	ini_write_real("BTDX", "trackmilestone4", global.track4milestone);
	ini_write_real("BTDX", "trackmilestone5", global.track5milestone);
	ini_write_real("BTDX", "trackmilestone6", global.track6milestone);
	ini_write_real("BTDX", "trackmilestone7", global.track7milestone);
	ini_write_real("BTDX", "trackmilestone8", global.track8milestone);
	ini_write_real("BTDX", "trackmilestone9", global.track9milestone);
	ini_write_real("BTDX", "trackmilestone10", global.track10milestone);
	ini_write_real("BTDX", "trackmilestone11", global.track11milestone);
	ini_write_real("BTDX", "trackmilestone12", global.track12milestone);
	ini_write_real("BTDX", "trackmilestone13", global.track13milestone);
	ini_write_real("BTDX", "trackmilestone14", global.track14milestone);
	ini_write_real("BTDX", "trackmilestone15", global.track15milestone);
	ini_write_real("BTDX", "trackmilestone16", global.track16milestone);
	ini_write_real("BTDX", "trackimpopmilestone1", global.track1hardstone);
	ini_write_real("BTDX", "trackimpopmilestone2", global.track2hardstone);
	ini_write_real("BTDX", "trackimpopmilestone3", global.track3hardstone);
	ini_write_real("BTDX", "trackimpopmilestone4", global.track4hardstone);
	ini_write_real("BTDX", "trackimpopmilestone5", global.track5hardstone);
	ini_write_real("BTDX", "trackimpopmilestone6", global.track6hardstone);
	ini_write_real("BTDX", "trackimpopmilestone7", global.track7hardstone);
	ini_write_real("BTDX", "trackimpopmilestone8", global.track8hardstone);
	ini_write_real("BTDX", "trackimpopmilestone9", global.track9hardstone);
	ini_write_real("BTDX", "trackimpopmilestone10", global.track10hardstone);
	ini_write_real("BTDX", "trackimpopmilestone11", global.track11hardstone);
	ini_write_real("BTDX", "trackimpopmilestone12", global.track12hardstone);
	ini_write_real("BTDX", "trackimpopmilestone13", global.track13hardstone);
	ini_write_real("BTDX", "trackimpopmilestone14", global.track14hardstone);
	ini_write_real("BTDX", "trackimpopmilestone15", global.track15hardstone);
	ini_write_real("BTDX", "trackimpopmilestone16", global.track16hardstone);
	ini_write_real("BTDX", "specialcheck1", global.specialmission1);
	ini_write_real("BTDX", "specialcheck2", global.specialmission2);
	ini_write_real("BTDX", "specialcheck3", global.specialmission3);
	ini_write_real("BTDX", "specialcheck4", global.specialmission4);
	ini_write_real("BTDX", "specialcheck5", global.specialmission5);
	ini_write_real("BTDX", "specialcheck6", global.specialmission6);
	ini_write_real("BTDX", "specialcheck7", global.specialmission7);
	ini_write_real("BTDX", "specialcheck8", global.specialmission8);
	ini_write_real("BTDX", "specialcheck9", global.specialmission9);
	ini_write_real("BTDX", "specialcheck10", global.specialmission10);
	ini_write_real("BTDX", "specialcheck11", global.specialmission11);
	ini_write_real("BTDX", "specialcheck12", global.specialmission12);
	ini_write_real("BTDX", "trackbestwave1", global.track1bestwave);
	ini_write_real("BTDX", "trackbestwave2", global.track2bestwave);
	ini_write_real("BTDX", "trackbestwave3", global.track3bestwave);
	ini_write_real("BTDX", "trackbestwave4", global.track4bestwave);
	ini_write_real("BTDX", "trackbestwave5", global.track5bestwave);
	ini_write_real("BTDX", "trackbestwave6", global.track6bestwave);
	ini_write_real("BTDX", "trackbestwave7", global.track7bestwave);
	ini_write_real("BTDX", "trackbestwave8", global.track8bestwave);
	ini_write_real("BTDX", "trackbestwave9", global.track9bestwave);
	ini_write_real("BTDX", "trackbestwave10", global.track10bestwave);
	ini_write_real("BTDX", "trackbestwave11", global.track11bestwave);
	ini_write_real("BTDX", "trackbestwave12", global.track12bestwave);
	ini_write_real("BTDX", "trackbestwave13", global.track13bestwave);
	ini_write_real("BTDX", "trackbestwave14", global.track14bestwave);
	ini_write_real("BTDX", "trackbestwave15", global.track15bestwave);
	ini_write_real("BTDX", "trackbestwave16", global.track16bestwave);
	ini_write_real("BTDX", "trackbestimpopwave1", global.track1besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave2", global.track2besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave3", global.track3besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave4", global.track4besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave5", global.track5besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave6", global.track6besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave7", global.track7besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave8", global.track8besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave9", global.track9besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave10", global.track10besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave11", global.track11besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave12", global.track12besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave13", global.track13besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave14", global.track14besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave15", global.track15besthardwave);
	ini_write_real("BTDX", "trackbestimpopwave16", global.track16besthardwave);

	ini_write_real("BTDX", "trackbestnightwave1", global.track1bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave2", global.track2bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave3", global.track3bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave4", global.track4bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave5", global.track5bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave6", global.track6bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave7", global.track7bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave8", global.track8bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave9", global.track9bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave10", global.track10bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave11", global.track11bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave12", global.track12bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave13", global.track13bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave14", global.track14bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave15", global.track15bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave16", global.track16bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave17", global.track17bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave18", global.track18bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave19", global.track19bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave20", global.track20bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave21", global.track21bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave22", global.track22bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave23", global.track23bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave24", global.track24bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave25", global.track25bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave26", global.track26bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave27", global.track27bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave28", global.track28bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave29", global.track29bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave30", global.track30bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave31", global.track31bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave32", global.track32bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave33", global.track33bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave34", global.track34bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave35", global.track35bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave36", global.track36bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave37", global.track37bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave38", global.track38bestnightwave);
	ini_write_real("BTDX", "trackbestnightwave39", global.track39bestnightwave);

	ini_write_real("BTDX", "DM0", global.DML);
	ini_write_real("BTDX", "DM1", global.DMM);
	ini_write_real("BTDX", "DM2", global.DMR);
	ini_write_real("BTDX", "TS0", global.TSL);
	ini_write_real("BTDX", "TS1", global.TSM);
	ini_write_real("BTDX", "TS2", global.TSR);
	ini_write_real("BTDX", "BM0", global.BML);
	ini_write_real("BTDX", "BM1", global.BMM);
	ini_write_real("BTDX", "BM2", global.BMR);
	ini_write_real("BTDX", "SnM0", global.SnML);
	ini_write_real("BTDX", "SnM1", global.SnMM);
	ini_write_real("BTDX", "SnM2", global.SnMR);
	ini_write_real("BTDX", "NM0", global.NML);
	ini_write_real("BTDX", "NM1", global.NMM);
	ini_write_real("BTDX", "NM2", global.NMR);
	ini_write_real("BTDX", "BC0", global.BCL);
	ini_write_real("BTDX", "BC1", global.BCM);
	ini_write_real("BTDX", "BC2", global.BCR);
	ini_write_real("BTDX", "MS0", global.MSL);
	ini_write_real("BTDX", "MS1", global.MSM);
	ini_write_real("BTDX", "MS2", global.MSR);
	ini_write_real("BTDX", "CT0", global.CTL);
	ini_write_real("BTDX", "CT1", global.CTM);
	ini_write_real("BTDX", "CT2", global.CTR);

	ini_write_real("BTDX", "GG0", global.GGL);
	ini_write_real("BTDX", "GG1", global.GGM);
	ini_write_real("BTDX", "GG2", global.GGR);
	ini_write_real("BTDX", "IM0", global.IML);
	ini_write_real("BTDX", "IM1", global.IMM);
	ini_write_real("BTDX", "IM2", global.IMR);
	ini_write_real("BTDX", "MB0", global.MBL);
	ini_write_real("BTDX", "MB1", global.MBM);
	ini_write_real("BTDX", "MB2", global.MBR);
	ini_write_real("BTDX", "ME0", global.MEL);
	ini_write_real("BTDX", "ME1", global.MEM);
	ini_write_real("BTDX", "ME2", global.MER);
	ini_write_real("BTDX", "MA0", global.MAL);
	ini_write_real("BTDX", "MA1", global.MAM);
	ini_write_real("BTDX", "MA2", global.MAR);
	ini_write_real("BTDX", "BCh0", global.BChL);
	ini_write_real("BTDX", "BCh1", global.BChM);
	ini_write_real("BTDX", "BCh2", global.BChR);
	ini_write_real("BTDX", "MAp0", global.MApL);
	ini_write_real("BTDX", "MAp1", global.MApM);
	ini_write_real("BTDX", "MAp2", global.MApR);
	ini_write_real("BTDX", "MAl0", global.MAlL);
	ini_write_real("BTDX", "MAl1", global.MAlM);
	ini_write_real("BTDX", "MAl2", global.MAlR);

	ini_write_real("BTDX", "MV0", global.MVL);
	ini_write_real("BTDX", "MV1", global.MVM);
	ini_write_real("BTDX", "MV2", global.MVR);
	ini_write_real("BTDX", "BT0", global.BTL);
	ini_write_real("BTDX", "BT1", global.BTM);
	ini_write_real("BTDX", "BT2", global.BTR);
	ini_write_real("BTDX", "DG0", global.DGL);
	ini_write_real("BTDX", "DG1", global.DGM);
	ini_write_real("BTDX", "DG2", global.DGR);
	ini_write_real("BTDX", "ML0", global.MLL);
	ini_write_real("BTDX", "ML1", global.MLM);
	ini_write_real("BTDX", "ML2", global.MLR);
	ini_write_real("BTDX", "HP0", global.HPL);
	ini_write_real("BTDX", "HP1", global.HPM);
	ini_write_real("BTDX", "HP2", global.HPR);
	ini_write_real("BTDX", "SF0", global.SFL);
	ini_write_real("BTDX", "SF1", global.SFM);
	ini_write_real("BTDX", "SF2", global.SFR);
	ini_write_real("BTDX", "PM0", global.PML);
	ini_write_real("BTDX", "PM1", global.PMM);
	ini_write_real("BTDX", "PM2", global.PMR);
	ini_write_real("BTDX", "SuM0", global.SuML);
	ini_write_real("BTDX", "SuM1", global.SuMM);
	ini_write_real("BTDX", "SuM2", global.SuMR);

	ini_write_real("BTDX", "Agents0", global.angrysquirrel);
	ini_write_real("BTDX", "Agents1", global.bloonburybush);
	ini_write_real("BTDX", "Agents2", global.sprinkler);
	ini_write_real("BTDX", "Agents3", global.monkeynurse);
	ini_write_real("BTDX", "Agents4", global.bananamobile);
	ini_write_real("BTDX", "careershow", global.careershow);


	ini_write_real("BTDX", "bountycheck1", global.b1);
	ini_write_real("BTDX", "bountycheck2", global.b2);
	ini_write_real("BTDX", "bountycheck3", global.b3);
	ini_write_real("BTDX", "bountycheck4", global.b4);
	ini_write_real("BTDX", "bountycheck5", global.b5);
	ini_write_real("BTDX", "bountycheck6", global.b6);
	ini_write_real("BTDX", "bountycheck7", global.b7);
	ini_write_real("BTDX", "bountycheck8", global.b8);
	ini_write_real("BTDX", "bountycheck9", global.b9);
	ini_write_real("BTDX", "bountycheck10", global.b10);
	ini_write_real("BTDX", "bountycheck11", global.b11);
	ini_write_real("BTDX", "bountycheck12", global.b12);
	ini_write_real("BTDX", "bountycheck13", global.b13);
	ini_write_real("BTDX", "bountycheck14", global.b14);
	ini_write_real("BTDX", "bountycheck15", global.b15);
	ini_write_real("BTDX", "bountycheck16", global.b16);

	ini_write_real("BTDX", "trackscore1", global.x1);
	ini_write_real("BTDX", "trackscore2", global.x2);
	ini_write_real("BTDX", "trackscore3", global.x3);
	ini_write_real("BTDX", "trackscore4", global.x4);
	ini_write_real("BTDX", "trackscore5", global.x5);
	ini_write_real("BTDX", "trackscore6", global.x6);
	ini_write_real("BTDX", "trackscore7", global.x7);
	ini_write_real("BTDX", "trackscore8", global.x8);
	ini_write_real("BTDX", "trackscore9", global.x9);
	ini_write_real("BTDX", "trackscore10", global.x10);
	ini_write_real("BTDX", "trackscore11", global.x11);
	ini_write_real("BTDX", "trackscore12", global.x12);
	ini_write_real("BTDX", "trackscore13", global.x13);
	ini_write_real("BTDX", "trackscore14", global.x14);
	ini_write_real("BTDX", "trackscore15", global.x15);
	ini_write_real("BTDX", "trackscore16", global.x16);

	ini_write_real("BTDX", "tracktime1", global.t1);
	ini_write_real("BTDX", "tracktime2", global.t2);
	ini_write_real("BTDX", "tracktime3", global.t3);
	ini_write_real("BTDX", "tracktime4", global.t4);
	ini_write_real("BTDX", "tracktime5", global.t5);
	ini_write_real("BTDX", "tracktime6", global.t6);
	ini_write_real("BTDX", "tracktime7", global.t7);
	ini_write_real("BTDX", "tracktime8", global.t8);
	ini_write_real("BTDX", "tracktime9", global.t9);
	ini_write_real("BTDX", "tracktime10", global.t10);
	ini_write_real("BTDX", "tracktime11", global.t11);
	ini_write_real("BTDX", "tracktime12", global.t12);
	ini_write_real("BTDX", "tracktime13", global.t13);
	ini_write_real("BTDX", "tracktime14", global.t14);
	ini_write_real("BTDX", "tracktime15", global.t15);
	ini_write_real("BTDX", "tracktime16", global.t16);

	/*
	ini_write_real("BTDX", "xx1", global.xx1);
	ini_write_real("BTDX", "xx2", global.xx2);
	ini_write_real("BTDX", "xx3", global.xx3);
	ini_write_real("BTDX", "xx4", global.xx4);
	ini_write_real("BTDX", "xx5", global.xx5);
	ini_write_real("BTDX", "xx6", global.xx6);
	ini_write_real("BTDX", "xx7", global.xx7);
	ini_write_real("BTDX", "xx8", global.xx8);
	ini_write_real("BTDX", "xx9", global.xx9);
	ini_write_real("BTDX", "xx10", global.xx10);
	ini_write_real("BTDX", "xx11", global.xx11);
	ini_write_real("BTDX", "xx12", global.xx12);
	ini_write_real("BTDX", "xx13", global.xx13);
	ini_write_real("BTDX", "xx14", global.xx14);
	ini_write_real("BTDX", "xx15", global.xx15);
	ini_write_real("BTDX", "xx16", global.xx16);
	*/

	ini_write_real("BTDX", "challengecheck1", global.c1);
	ini_write_real("BTDX", "challengecheck2", global.c2);
	ini_write_real("BTDX", "challengecheck3", global.c3);
	ini_write_real("BTDX", "challengecheck4", global.c4);
	ini_write_real("BTDX", "challengecheck5", global.c5);
	ini_write_real("BTDX", "challengecheck6", global.c6);
	ini_write_real("BTDX", "challengecheck101", global.c101);
	ini_write_real("BTDX", "challengecheck102", global.c102);
	ini_write_real("BTDX", "challengecheck103", global.c103);
	ini_write_real("BTDX", "challengecheck104", global.c104);
	ini_write_real("BTDX", "challengecheck105", global.c105);
	ini_write_real("BTDX", "challengecheck106", global.c106);

	ini_write_real("BTDX", "tracknightmaremilestone1", global.track1nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone2", global.track2nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone3", global.track3nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone4", global.track4nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone5", global.track5nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone6", global.track6nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone7", global.track7nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone8", global.track8nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone9", global.track9nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone10", global.track10nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone11", global.track11nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone12", global.track12nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone13", global.track13nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone14", global.track14nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone15", global.track15nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone16", global.track16nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone17", global.track17nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone18", global.track18nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone19", global.track19nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone20", global.track20nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone21", global.track21nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone22", global.track22nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone23", global.track23nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone24", global.track24nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone25", global.track25nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone26", global.track26nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone27", global.track27nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone28", global.track28nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone29", global.track29nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone30", global.track30nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone31", global.track31nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone32", global.track32nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone33", global.track33nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone34", global.track34nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone35", global.track35nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone36", global.track36nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone37", global.track37nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone38", global.track38nightstone);
	ini_write_real("BTDX", "tracknightmaremilestone39", global.track39nightstone);

	ini_write_real("BTDX", "goodiecheck1", global.goodie1);
	ini_write_real("BTDX", "goodiecheck2", global.goodie2);
	ini_write_real("BTDX", "goodiecheck3", global.goodie3);
	ini_write_real("BTDX", "goodiecheck4", global.goodie4);
	ini_write_real("BTDX", "goodiecheck5", global.goodie5);
	ini_write_real("BTDX", "goodiecheck6", global.goodie6);
	ini_write_real("BTDX", "goodiecheck7", global.goodie7);
	ini_write_real("BTDX", "goodiecheck8", global.goodie8);
	ini_write_real("BTDX", "goodiecheck9", global.goodie9);
	ini_write_real("BTDX", "goodiecheck10", global.goodie10);
	ini_write_real("BTDX", "goodiecheck11", global.goodie11);
	ini_write_real("BTDX", "goodiecheck12", global.goodie12);
	ini_write_real("BTDX", "goodiecheck13", global.goodie13);
	ini_write_real("BTDX", "goodiecheck14", global.goodie14);
	ini_write_real("BTDX", "goodiecheck15", global.goodie15);
	ini_write_real("BTDX", "goodiecheck16", global.goodie16);


	ini_write_real("BTDX", "bsouls", global.bsouls);
	ini_write_real("BTDX", "trophies", global.trophies);


	
	ini_close();


}
